"use client";

//import type { Metadata } from "next";
//import localFont from "next/font/local";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { useState, ReactNode } from "react";
import { menuItems } from "../data/menuItems";
import Sidebar from "../components/SideBar";
import MainContent from "../components/MainContent";

/*const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});*/

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

const notoSans = Noto_Sans({
  subsets: ["latin"], // Specify the subsets to be used
  weight: ["400", "700"], // Optionally specify the font weights
  variable: "--font-noto-sans", // Optionally create a CSS variable for the font
});

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const [isSidebarOpen, setSidebarOpen] = useState(false);

  const toggleSidebar = () => {
    setSidebarOpen(!isSidebarOpen);
  };

  return (
    <html lang="en">
      <body className={`${notoSans.className} antialiased flex h-screen`}>
        <div className="md:hidden fixed top-0 left-0 right-0 bg-gray-800 text-white p-4 flex items-center justify-between z-50">
          <span className="text-lg font-semibold">Bookshop API</span>
          <button
            className="bg-blue-500 text-white p-2 rounded focus:outline-none focus:ring-2 focus:ring-blue-300 hover:bg-blue-600 transition"
            onClick={toggleSidebar}
          >
            Menu
          </button>
        </div>
        <div
          className={`md:flex ${
            isSidebarOpen ? "flex" : "hidden"
          } fixed top-16 left-0 md:static h-full md:h-auto z-40`}
        >
          <Sidebar
            menuItems={menuItems}
            className="bg-gray-900 md:w-64 transition-transform"
          />
        </div>
        <MainContent>
          <div className="pt-16 md:pt-0 prose dark:prose-invert">
            {children}
          </div>
        </MainContent>

        {isSidebarOpen && (
          <div
            className="fixed inset-0 top-16 bg-black bg-opacity-50 z-30 md:hidden"
            onClick={toggleSidebar}
          />
        )}
      </body>
    </html>
  );
}
